conda-forge/autogluon.multimodal-feedstock

- recipe/meta.yaml
> Added additional maintainer

- recipe/meta.yaml
> Fix torchtext error on arm64

- recipe/meta.yaml
https://github.com/conda-forge/nlpaug-feedstock/pull/7
> Updated nlpaug version to support pytorch-gpu

- recipe/meta.yaml
> Loose version bound of nlpaug

- recipe/meta.yaml
> Loose pytorch version upper bound

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cuda_compiler_version11.2python3.10.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_version11.2python3.8.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_version11.2python3.9.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonepython3.10.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonepython3.8.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonepython3.9.____cpython.yaml
- .ci_support/osx_64_python3.10.____cpython.yaml
- .ci_support/osx_arm64_python3.10.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- README.md
- recipe/meta.yaml
> Prep for v0.7.0

- .ci_support/linux_64_cuda_compiler_version11.2python3.10.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_version11.2python3.8.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_version11.2python3.9.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonepython3.10.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonepython3.8.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonepython3.9.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/meta.yaml
> Update to v0.8.0

- recipe/meta.yaml
> increase pytorch upper bound

- recipe/meta.yaml
> upgrade jsonschema

- recipe/meta.yaml
> upgrade scikit-learn

- recipe/meta.yaml
> rebase to v1.1.1

- recipe/meta.yaml
> upgrade scikit-image

- recipe/meta.yaml
> patch 0.8.3 to upgrade jsonschema

- recipe/meta.yaml
> patch 0.8.3 to upgrade transformers for CVE patch

- recipe/meta.yaml
> upgrade transformer

- recipe/meta.yaml
> upgrade accelerate v1.1.0

- recipe/meta.yaml
> upgrade transformer and accelerate

- recipe/meta.yaml
> upgrade to pytorch-lightning 2.4 for AGv0.8.3

- recipe/meta.yaml
> Release 0.8.3

- recipe/meta.yaml
> Downgrade Transformers

- .ci_support/linux_64_.yaml
- .github/CODEOWNERS
- .gitignore
- .scripts/run_docker_build.sh
- README.md
- build-locally.py
- recipe/meta.yaml
> Release 1.3.0

- recipe/meta.yaml
> Update PyTorch to 2.7 and torchvision to 0.22
